---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: helm-chart-sonarqube
  namespace: dpe-sonarqube
spec:
  interval: 5m0s
  ref:
    branch: master
  url: https://github.com/SonarSource/helm-chart-sonarqube.git
