---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube-local-helmrelease
  namespace: sonarqube
spec:
  chart:
    spec:
      chart: charts/sonarqube
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: helm-chart-sonarqube
  interval: 5m0s
  values:
    ingress:
      enabled: true
      hosts:
      - name: sonarqube.app.local
        path: /
    postgresql:
      enabled: true
      postgresqlUsername: "sonarUser"
      postgresqlPassword: "sonarPass"
      postgresqlDatabase: "sonarDB"
      persistence:
        enabled: true
        accessMode: ReadWriteOnce
        size: 20Gi
        storageClass:
      securityContext:
        enabled: true
        fsGroup: 1001
      containerSecurityContext:
        enabled: true
        runAsUser: 1001
      volumePermissions:
        enabled: false
        securityContext:
          runAsUser: 0
      shmVolume:
        chmod:
          enabled: false
      service:
        port: 5432
    # sonarProperties:
    #   ldap.group.baseDn: DC=example,DC=com
    #   ldap.group.idAttribute: SamAccountName
    #   ldap.group.request: (&(objectClass=group)(member={dn}))
    #   ldap.url: ldaps://dc01.example.com:3269
    #   ldap.user.baseDn: DC=example,DC=com
    #   ldap.user.emailAttribute: mail
    #   ldap.user.realNameAttribute: Name
    #   ldap.user.request: (&(objectClass=user)(SamAccountName={login}))
    #   ldap.StartTLS: false
    #   sonar.security.realm: LDAP
    # sonarSecretProperties: sonarqube-ad-secrets
    startupProbe:
      failureThreshold: 30
      initialDelaySeconds: 60
      periodSeconds: 30
