apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- metrics-server-components.yaml
- ingress-controller.yaml
- sonarqube-serviceaccount.yaml
- sonarqube-gitrepository.yaml
- sonarqube-helmrelease.yaml
- openldap-serviceaccount.yaml
- openldap-gitrepository.yaml
- openldap-helmrelease.yaml
