---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap-local-helmrelease
  namespace: identity
spec:
  values:
    image:
      repository: osixia/openldap
      tag: 1.5.0
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
      - name: openldap.app.local
        path: /
    tls:
      enabled: false
      secret: ""  # The name of a kubernetes.io/tls type secret to use for TLS
      CA:
        enabled: false
        secret: ""  # The name of a generic secret to use for custom CA certificate (ca.crt)
    ## Add additional labels to all resources
    extraLabels: {}
    ## Add additional annotations to pods
    podAnnotations: {}
    service:
      annotations: {}
      clusterIP: ""

      ldapPort: 389
      sslLdapPort: 636  # Only used if tls.enabled is true
      ## List of IP addresses at which the service is available
      ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
      ##
      externalIPs: []

      loadBalancerIP: ""
      loadBalancerSourceRanges: []
      type: ClusterIP

    # Default configuration for openldap as environment variables. These get injected directly in the container.
    # Use the env variables from https://github.com/osixia/docker-openldap#beginner-guide
    env:
      LDAP_ORGANISATION: "devops"
      LDAP_DOMAIN: "openldap.app.local"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_ENFORCE: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: readonly
      LDAP_READONLY_USER_MASSWORD: password

    # Default Passwords to use, stored as a secret. If unset, passwords are auto-generated.
    # You can override these at install time with
    # helm install openldap --set openldap.adminPassword=<passwd>,openldap.configPassword=<passwd>
    adminPassword: password
    configPassword: password

    # Custom openldap configuration files used to override default settings
    customLdifFiles:
      0-initial-ous.ldif: |-
        dn: ou=devops,dc=openldap,dc=app,dc=local
        objectClass: organizationalUnit
        ou: devops
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi
