---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: helm-chart-openldap
  namespace: identity
spec:
  interval: 5m0s
  ref:
    branch: master
  url: https://github.com/jp-gouin/helm-openldap.git
