---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/part-of: identity
  name: openldap-gitops
  namespace: identity
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openldap-api-cluster-role
  namespace: identity
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openldap-api-cluster-role-binding
  namespace: identity
subjects:
- namespace: identity
  kind: ServiceAccount
  name: openldap-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openldap-api-cluster-role
