---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/part-of: sonarqube
  name: sonarqube-gitops
  namespace: sonarqube
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sonarqube-api-cluster-role
  namespace: sonarqube
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sonarqube-api-cluster-role-binding
  namespace: sonarqube
subjects:
- namespace: sonarqube
  kind: ServiceAccount
  name: sonarqube-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sonarqube-api-cluster-role
